services:
  api-compose:
    build: . 
    ports: 
      - "6969:6969"
    volumes: 
      - type: bind 
        source: ../db/
        target: /db
#     build: .
#     ports:
#       - "2222:2222"
#     volumes:
#       - post-volume:/frontend-posts
#     secrets:
#       - authorized_key_file

# secrets:
#   authorized_key_file:
#     file: ~/.ssh/authorized_keys